%% engineering_analysis.m
% Q6: Final CO1-CO5 summary and engineering interpretation.
% Assumes Q1-Q5 and validation.m have already been executed in this session.

fprintf('\n============================================================\n');
fprintf(' ENGINEERING ANALYSIS AND CO1-CO5 SUMMARY\n');
fprintf('============================================================\n');

fprintf(['\nCO1 (Newton''s Method): The nonlinear steady-state energy balance\n' ...
    'of the flat-plate collector converges to a stable operating\n' ...
    'temperature of %.4f deg C in %d iterations. Quadratic convergence is\n' ...
    'evident: the error shrinks from ~%.3f C to ~%.3e C within 3 steps,\n' ...
    'confirming the nonlinear radiative-loss term is well-conditioned near\n' ...
    'the root and that the derivative never approaches zero in this range.\n'], ...
    Q1_results.T_root, Q1_results.iterCount, Q1_results.iterTable(1,6), Q1_results.iterTable(end,6));

fprintf(['\nCO2 (Newton Forward Interpolation): The missing sensor reading at\n' ...
    't = %g min is estimated as %.3f deg C, matching the built-in spline\n' ...
    'reference to within %.4f deg C. Because the third and fourth forward\n' ...
    'differences are ~0, the underlying data is well represented by a\n' ...
    'quadratic, so truncating the Newton series after the second-order\n' ...
    'term introduces negligible error.\n'], ...
    Q2_results.t_query, Q2_results.T_est, abs(Q2_results.T_est - Q2_results.T_builtin));

fprintf(['\nCO3 (Simpson''s 1/3 Rule): Total heat collected over the 60-minute\n' ...
    'window is %.3f MJ (%.3f kWh), within %.4f%% of the trapezoidal\n' ...
    'reference integral. The close agreement indicates the irradiance\n' ...
    'profile is smooth enough over the 10-minute sampling interval that\n' ...
    'Simpson''s parabolic approximation introduces very low integration\n' ...
    'error.\n'], Q3_results.Q_MJ, Q3_results.Q_kWh, ...
    100*abs(Q3_results.Q_joules-Q3_results.Q_trapz)/Q3_results.Q_joules);

fprintf(['\nCO4 (RK4): The lumped-capacitance thermal model predicts the\n' ...
    'collector temperature rises from %.1f deg C to %.4f deg C over one\n' ...
    'hour, tracking the closed-form analytical exponential solution to\n' ...
    'within %.2e deg C (max %.6f%% error). This confirms RK4''s fourth-order\n' ...
    'accuracy is more than sufficient for this linear ODE at h = %d s.\n'], ...
    35, Q4_results.TOut(end), max(Q4_results.absErr), max(Q4_results.pctErr), 600);

fprintf(['\nCO5 (Explicit Finite Difference): With r = %.4f (<= 0.5), the\n' ...
    'explicit FTCS scheme is stable and dt = 400 s is safely within the\n' ...
    'theoretical stability limit dt_max = %.2f s. The temperature field\n' ...
    'diffuses smoothly from the initial uniform 30 deg C interior toward\n' ...
    'the fixed boundary values (80 deg C / 40 deg C) without oscillation,\n' ...
    'consistent with a stable diffusion process. Halving dt changes the\n' ...
    'final-time solution by at most %.4f deg C, indicating the chosen grid\n' ...
    'already resolves the transient adequately.\n'], ...
    Q5_results.r, Q5_results.dt_max, max(Q5_results.diffFinal));

fprintf(['\n--- Engineering Usefulness ---\n' ...
    'Together, these five methods give a coherent, low-cost simulation\n' ...
    'workflow for a solar water-heating collector: Newton''s method sizes\n' ...
    'the steady operating point, interpolation recovers missing sensor\n' ...
    'data, Simpson''s rule quantifies delivered energy for performance\n' ...
    'reporting, RK4 predicts transient warm-up behaviour, and the finite-\n' ...
    'difference model captures spatial temperature gradients across the\n' ...
    'absorber. This supports preliminary sizing, sensor-data validation,\n' ...
    'and control-strategy development.\n']);

fprintf(['\n--- Model Limitations ---\n' ...
    'The lumped-capacitance and 1-D diffusion models neglect spatial\n' ...
    'non-uniformity of irradiance, wind-dependent convective losses,\n' ...
    'thermal stratification in the storage tank, and time-varying solar\n' ...
    'input (constant G was assumed within each sub-problem). The\n' ...
    'representative parameter values are engineering assumptions, not\n' ...
    'manufacturer-supplied or measured data, so results are indicative for\n' ...
    'coursework and preliminary design only -- NOT sufficient for detailed\n' ...
    'commercial certification or safety-critical sizing.\n']);

% --- Final CO summary table ---
fprintf('\n============================================================\n');
fprintf(' Final CO1-CO5 Summary Table\n');
fprintf('============================================================\n');
fprintf('%-6s %-30s %-25s %-15s\n', 'CO', 'Method', 'Key Result', 'Status');
fprintf('%-6s %-30s %-25s %-15s\n', 'CO1', 'Newton''s Method', sprintf('T = %.4f C', Q1_results.T_root), 'Converged');
fprintf('%-6s %-30s %-25s %-15s\n', 'CO2', 'Newton Forward Interp.', sprintf('T(15) = %.3f C', Q2_results.T_est), 'Validated');
fprintf('%-6s %-30s %-25s %-15s\n', 'CO3', 'Simpson''s 1/3 Rule', sprintf('Q = %.3f MJ', Q3_results.Q_MJ), 'Validated');
fprintf('%-6s %-30s %-25s %-15s\n', 'CO4', 'RK4', sprintf('T(end) = %.3f C', Q4_results.TOut(end)), 'Validated');
fprintf('%-6s %-30s %-25s %-15s\n', 'CO5', 'Explicit FDM', sprintf('r = %.3f (stable)', Q5_results.r), 'Stable');

fprintf('\n[Engineering Analysis] Complete.\n');
